# Generated by Django 2.0.13 on 2019-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10, null=True)),
                ('last', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
