# Generated by Django 2.2.2 on 2019-06-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('emp_ID', models.IntegerField(null=True, verbose_name='Employee ID')),
                ('emp_email', models.EmailField(max_length=254, null=True, verbose_name='Employee Email')),
                ('keycode', models.PositiveSmallIntegerField(default=0)),
                ('manager_email', models.EmailField(default='', max_length=254)),
                ('emp_permissions', models.CharField(choices=[(0, 'Never'), (1, 'Sometimes'), (2, 'Always')], default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TempPhoto',
            fields=[
                ('temp_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('unknown_photo', models.ImageField(null=True, upload_to='Temp Photos/')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='Dataset/')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Employee')),
            ],
        ),
    ]
