# Generated by Django 2.2.2 on 2019-06-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='primary_key',
            new_name='emp_ID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='authen',
        ),
    ]
