# Generated by Django 2.2.2 on 2019-06-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='badge_photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Employee'),
        ),
    ]
