# Generated by Django 2.2.2 on 2019-06-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190617_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='test@default.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='keycode',
            field=models.IntegerField(default=0),
        ),
    ]
