# Generated by Django 2.2.2 on 2019-06-17 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190617_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='cat.jpg', upload_to='pictures/'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Employee')),
            ],
        ),
    ]
