# Generated by Django 2.2.2 on 2019-06-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190617_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pic',
        ),
        migrations.AddField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='cat.jpg', upload_to='pictures/'),
        ),
    ]
