# Generated by Django 2.2.2 on 2019-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190621_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_permissions',
            field=models.CharField(choices=[('0', 'Never'), ('1', 'Sometimes'), ('2', 'Always')], default=0, max_length=15, verbose_name='Employee Permissions'),
        ),
    ]
