# Generated by Django 2.2.2 on 2019-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20190621_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Employee email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_permissions',
            field=models.CharField(choices=[('0', 'Never'), ('1', 'Sometimes'), ('2', 'Always')], default=0, max_length=15, verbose_name='Employee permissions'),
        ),
        migrations.AlterField(
            model_name='tempphoto',
            name='temp_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='Temporary ID'),
        ),
    ]
