# Generated by Django 2.2.2 on 2019-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20190621_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_time',
            field=models.DateField(null=True, verbose_name='Last login date'),
        ),
    ]
