# Generated by Django 2.2.2 on 2019-06-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_employee_login_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='login_time',
            new_name='last_login',
        ),
    ]
