# Generated by Django 2.2.2 on 2019-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20190617_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(default='cat.jpg', upload_to='Dataset'),
        ),
    ]
