# Generated by Django 2.2.2 on 2019-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20190618_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='cat.jpg', max_length=30),
        ),
    ]
