# Generated by Django 2.2.2 on 2019-06-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
