# Generated by Django 2.2.2 on 2019-06-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_remove_picture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='pic',
            new_name='picture',
        ),
    ]
