# Generated by Django 2.2.2 on 2019-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='dataset/'),
        ),
    ]
