# Generated by Django 2.2.2 on 2019-06-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20190618_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_ID',
            new_name='varen_ID',
        ),
    ]
