# Generated by Django 2.2.2 on 2019-06-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20190618_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Employee'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
