# Generated by Django 2.2.2 on 2019-06-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20190619_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
