# Generated by Django 2.2.2 on 2019-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_remove_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
