# Generated by Django 2.2.2 on 2019-06-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_picture_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='num',
        ),
    ]
