# Generated by Django 2.2.2 on 2019-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_remove_picture_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
