# Generated by Django 2.2.2 on 2019-06-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20190619_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='varen_ID',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
