# Generated by Django 2.2.2 on 2019-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20190619_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_ID',
            field=models.IntegerField(default=0, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
