# Generated by Django 2.2.2 on 2019-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20190619_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_ID',
            field=models.IntegerField(null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
