# Generated by Django 2.2.2 on 2019-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_auto_20190620_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='path',
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='Dataset/'),
        ),
    ]
